name: Mi workflow

on: push

jobs:
  tareas:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar código
        uses: actions/checkout@v4

      - name: Probar código
        run: python3 main.py
